---
name: oci

on:
  push:
    tags:
      - "*" # triggers on all new tags

permissions:
  contents: write
  packages: write

jobs:
  buildx:
    needs: get_info
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          build-args: |
            version=6.5.0
